### ISSUE TITLE
Inconsistency between data that appears in preview/presentation, and what is shown in the configuration modal

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-google-spreadsheet#122] opened 2015-08-20 16:14 UTC
When viewing the configuration modal for the spreadsheet widgets, the data source (specifically the worksheet) doesn't match what is shown in a preview or on a display.
In this case (first item under specials, placeholder specials-01), the configuration indicates that it should be looking at worksheet tuesday, range c4:c4.  However, when previewing or on a display, the content is actually being pulled from the worksheet GH-WEDNESDAY.
I believe this is actually the correct data that the user is wanting.

Additional information from the community post letting us know about the issue:
"There are two sets of tabs in the Spreadsheet, the old ones (With no GH) and the new GH ones. The old ones are associated with an old presentation and none of the tabs have changed since I created the original NEW presentation (Which I then had to change into 7 separate presentations, which kicked off this issue)
Content of the spreadsheet changes every few days as they add and change the specials and daily items. Other than that, no changes."

Link to Community post:
https://community.risevision.com/rise_vision_inc/topics/spreadsheet-widget-displaying-wrong-sheets

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=7f05371f-c324-43df-a3a0-a437b816c658?cid=11d6d727-7c20-464f-b03f-6994986e8d54

OS:
Verified on Xubuntu & OSX

Chrome Ver:
44.0.2403.155

**Comment by donnapep** [comment] 2015-08-20 18:12
@mfisher11 Easy fix. Change the number of header rows from 1 to 0. There are no header rows in that worksheet and it throws everything off. Thx.

**Comment by donnapep** [comment] 2015-08-20 18:13
@mfisher11 Will let you close.

**Comment by donnapep** [comment] 2015-08-20 18:38
Taking another look since the header rows was only set to 1 in the test Presentation I was working from, but not in the Production version.

**Comment by alanclayton** [comment] 2015-08-24 22:25
Issue caused by an anomaly event that resulted in the incorrect data source URL being saved with an instance of the Google Spreadsheet Widget. Per the comment in the Community, resolved by re saving the Widget Settings.

**Closed by alanclayton** 2015-08-24 22:25 UTC
Labels: bug
