### ISSUE TITLE
Scrolling is unreliable when used with custom refresh intervals.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#248] opened 2016-11-14 19:35 UTC
**How to recreate the problem**

1. Add a google spreadsheet widget to a presentation, add an API key to that widget, set the refresh interval to 5 minutes.
2. Set the Scroll to continuously, slow.
3. Publish presentation and assign it to a display.

**What happens**
Within 5 minutes, the spreadsheet scroll slows significantly, and after scrolling through spreadsheet, does not start over at the top of the sheet.

**What should happen**
The spreadsheet should continually scroll at the same rate, starting over at the top every time.

**Community topic**
https://community.risevision.com/rise_vision_inc/topics/google-sheet-scrolling-breaks?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_18002943

**Presentation**
https://goo.gl/5CUykf

**Notes**
Windows 10 x64, 
Player Version: RisePlayerElectron 2016.11.03.15.19
Viewer Version: 2-01-201611092223

**Comment by leaninonlife** [comment] 2016-11-14 20:25
For temporary patch to bypass the issue during the fix, you can simply change your refresh time to 60+ minutes while maintaining your API key until the problem is resolved.

**Comment by donnapep** [comment] 2016-11-15 19:25
Fixed by rolling back #246.

**Closed by donnapep** 2016-11-15 19:25 UTC
Labels: bug
