### ISSUE TITLE
After updating spreadsheet content with numeric content, data layout breaks

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-google-spreadsheet#119] opened 2015-06-30 17:19 UTC
Steps to reproduce:
1. Start with a working presentation that correctly displays content from a google spreadsheet
2. Modify the spreadsheet by adding a numeric value

Result:
When widget updates, content layout is broken and data is missing/hidden
* I've attached before and after screenshots to illustrate the problem.  The only difference between the two was the addition of the number "1" in cell A4.

How it should work:
Content should display correctly

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=61f43d61-6b3f-42ff-8a7e-09dc8af85268?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Ubuntu 14.04, Win7, Win8, OSX, ChromeOS

Chrome Ver:
Stable, Beta, Dev

![before](https://cloud.githubusercontent.com/assets/10407181/8436980/cda9337e-1f21-11e5-997b-de08f0fff5bc.png)
![after](https://cloud.githubusercontent.com/assets/10407181/8436985/d331f0b0-1f21-11e5-92bf-ec50084115eb.png)

**Comment by donnapep** [comment] 2015-07-01 18:02
@mfisher11 Can you share the spreadsheet with me? I haven't been able to reproduce so far. Thx.

**Comment by mfisher11** [comment] 2015-07-01 18:05
@donnapep You should be able to edit it now.

**Comment by donnapep** [comment] 2015-07-01 18:15
@mfisher11 Thanks. I actually still can't reproduce. What I get when I enter a number in A4 is a blank screen, which is issue #118. So I think you should retry after that issue is fixed, OK?

**Comment by mfisher11** [comment] 2015-07-01 18:21
@donnapep That's odd.  Well, a workaround would be to update the presentation--that (generally) was a one-shot that would fix the blank screen issue, and should at least allow you to replicate this one.

If this only affects numeric data and 118 affects *everything*, I think you're right about it being fixed first.  Do you agree @alanclayton ?

**Comment by alanclayton** [comment] 2015-07-01 18:43
Agreed

**Comment by donnapep** [comment] 2015-07-01 20:10
@mfisher11 I was able to reproduce by starting the Presentation up with a number in that field rather than adding the number after the Presentation was already running.

**Comment by donnapep** [comment] 2015-07-01 20:33
@mfisher11 Can you choose a different number of header rows besides "Auto". "Auto" shouldn't actually be an option as it's problematic.

**Comment by alanclayton** [comment] 2015-07-01 20:36
@donnapep @mfisher11 if Auto is a problem we should remove it and set default value to 1. @mfisher11 let us know. Thanks

**Comment by mfisher11** [comment] 2015-07-01 20:46
@donnapep @alanclayton  That was the problem.  I had left everything with the default, and "Auto" was the default setting.  Manually setting it to "0" or "1" keeps the formatting/visibility.

**Comment by mfisher11** [comment] 2015-07-01 21:47
@alanclayton Should I close this out since it's technically not a bug, or do you want to keep it open as history/context for removing "Auto" or changing the default?

**Comment by alanclayton** [comment] 2015-07-01 22:09
Just leave it open. We need to pull the option Auto and update default to
1. We'll close it when that work is done. Thanks

**Comment by stulees** [comment] 2015-08-25 14:38
@alanclayton FYI, closing this issue. The PRs referenced above contain the fix which was to remove "Auto" from the Header Row selection.

**Closed by stulees** 2015-08-25 14:38 UTC
Labels: bug
