### ISSUE TITLE
Spreadsheet Widget saying sheet is not public, even though it is.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#302] opened 2018-07-10 15:47 UTC
**What happens**

When a specific spreadsheet is added to a Spreadsheet Widget, it has the error message "To use this Google Spreadsheet it must be publicly accessible. To do this, open the Google Spreadsheet and select File > Share > Advanced, then select On - Anyone with the link." even when the Spreadsheet is set to public with link.

**What should happen**
Spreadsheet should not have the error message, and should appear in the Presentation Preview.

**Notes**
I will share the link to the Presentation and Spreadsheet in the card generated for Content.

**Comment by btfrise** [comment] 2018-07-10 15:48
![](https://github.trello.services/images/mini-trello-icon.png) [Spreadsheet Widget saying sheet is not public, even though it is.](https://trello.com/c/pY2oxrGE/8277-spreadsheet-widget-saying-sheet-is-not-public-even-though-it-is)

**Comment by sheadarlison** [comment] 2018-07-12 13:55
We believe this was a problem with Google's API. Closing the issue.

**Comment by robb-price** [comment] 2018-07-12 20:36
@sheadarlison Reopening this given the conversation in HipChat

_Stu: I think this warrants opening an issue. It is either a Google Sheets API bug or an issue on our side. Needs investigation._

**Comment by leaninonlife** [comment] 2018-07-18 14:48
Experiencing this issue still.

**Comment by sheadarlison** [comment] 2018-07-18 15:07
Hi Matthew, the issue is still ongoing you can follow updates in this community thread: 

https://help.risevision.com/hc/en-us/community/posts/360016993046

Thanks

**Comment by sheadarlison** [comment] 2018-07-20 12:50
Resolved by Google fixing this issue https://issuetracker.google.com/issues/111262653#comment77

**Closed by sheadarlison** 2018-07-20 12:50 UTC
Labels: bug
