### ISSUE TITLE
If a speadsheet cell is emptied, the widget stops refreshing

### ISSUE THREAD

**Issue by flickeringsight** [Rise-Vision/widget-google-spreadsheet#294] opened 2018-05-17 17:52 UTC
Lets say I launch a presentation with a spreadsheet widget set to update from a single cell with a refresh interval of 1 minute.  An API key is used.

- If the cell has content at launch time, changes made to the cell content **do** update the widget  as expected.
- If the cell has no content at launch time, additions and changes to the cell content **do** update the widget  as expected.
- But, if the cell is emptied of content during run time, the widget **does not** update as empty, and any subsequent additions or changes to the cell **does not** update the widget.

**Comment by sheadarlison** [comment] 2018-05-18 12:42
Hi @flickeringsight, 

Thanks for reporting this, I'm going to try and reproduce it today and then a developer will look into this issue early next week. Once they've looked into it they'll be able to give you an estimate for how long a fix will take. 

Let me know if you have any questions. 

Thanks,
Shea

**Comment by jungeunyoon** [comment] 2018-05-28 15:43
The fix has been deployed. @flickeringsight thanks for reporting.

---

###Problem 

- If a sheet with a single cell is emptied of content during run time, the widget does not update as empty, and any subsequent additions or changes to the cell does not update the widget.
- Throwing an error because trying to reference the `length` property of an empty dataset. 

###Solution 

- Added a check to see if the dataset is null and if so, setting column to 1

###How to validate 

Do one of the following: 
1. Add a new Video Widget.

**Closed** 2018-05-30 18:30 UTC
